const exec = async () => {

}
exec()
  .then(message => console.log('success', message))
  .catch(err => console.log('failed', err))
